# Cidre default fuzzel configuration
font=JetBrainsMono Nerd Font:size=12
prompt="❯ "
terminal=ghostty
width=30
horizontal-pad=20
vertical-pad=15
inner-pad=10

[colors]
background=1e1e2edd
text=cdd6f4ff
match=f38ba8ff
selection=585b70dd
selection-text=cdd6f4ff
border=b4befeef

[border]
width=2
radius=10
